name: 'Setup K6 and Kind'
description: 'Sets up K6 load testing tool and Kubernetes Kind'

inputs:
  kind-version:
    description: 'Kind version to use'
    required: false
    default: 'v0.27.0'
  k6-version:
    description: 'K6 version to use'
    required: false
    default: 'latest'
  kind-url:
    description: 'Custom URL to download Kind binary from'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install k6
      shell: bash
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        if [ "${{ inputs.k6-version }}" == "latest" ]; then
          sudo apt-get install k6
        else
          sudo apt-get install k6=${{ inputs.k6-version }}
        fi

    - name: Install Kind
      shell: bash
      run: |
        KIND_URL="${{ inputs.kind-url }}"
        if [ -z "$KIND_URL" ]; then
          KIND_URL="https://kind.sigs.k8s.io/dl/${{ inputs.kind-version }}/kind-linux-amd64"
        fi
        echo "Downloading Kind from $KIND_URL"
        curl -Lo ./kind "$KIND_URL"
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind