---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poolclaim-controller-role
rules:
- apiGroups:
  - "plexaubnet.io"
  resources:
  - subnetpoolclaims
  - subnetpoolclaims/status
  - subnetpoolclaims/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "plexaubnet.io"
  resources:
  - subnetpools
  - subnetclaims
  - subnets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete